//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineBook.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Book
    {
        public int id { get; set; }
        [MaxLength(24)]
        public string book_name { get; set; }
        public Nullable<int> pages { get; set; }
        public byte[] img { get; set; }
        public Nullable<int> cate_id { get; set; }
        public string book_url { get; set; }
        public virtual Category Category { get; set; }
    }
}
